Stylefixes
pawelniewie/zen2 pull request #1
Opened 2017-07-05 22:45 UTC by pavveu

Added some mixins, color scheme.
Create new project + top nav - styles fixed.

2017-07-06 07:56 UTC, pawelniewie requested changes
I haven't run it yet, will do that in the evening.

2017-07-06 07:56 UTC, pawelniewie commented on client/app/images/logo.svg
> +                    <polygon class="color_inline_logo_fill" id="Z" points="16.6094482 21.1606569 1.06085526 21.1606569 1.06085526 17.8381178 9.70199601 5.59646761 1.26562163 5.59646761 1.26562163 1.2
No BEM? :-D

2017-07-06 07:56 UTC, pawelniewie commented on client/app/layouts/focused-task.scss
>  .focused-task--header {
You could nest it in `.focused-task` with `&--header` makes it easier to maintain. Just FYI, no need to update it if you don't want.

2017-07-06 07:56 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +@mixin typo($font-size, $line-height, $font-weight:null) {
`typo` isn't that a typo? ;-)

2017-07-06 07:56 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +@mixin bck-color ($background, $color) {
`background-with-color` would be more meaningful?

2017-07-06 07:56 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +  -moz-border-radius: rem-calc($radius);
I don't think we need `-moz` and `-webkit`, I don't think we need to care about old versions of Safari and Firefox.

2017-07-06 07:56 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +  -webkit-transition: all 0.4s ease-in-out;
The same here and bellow.

2017-07-06 07:56 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +@mixin simple-button-wide($text-color, $bck-color: #ffffff, $border: null, $padding-horizontal: null, $padding-vertical: null) {
`simple-button` and `wide` could be merged or one extend the other?

2017-07-06 08:20 UTC, pavveu commented on client/app/images/logo.svg
> +                    <polygon class="color_inline_logo_fill" id="Z" points="16.6094482 21.1606569 1.06085526 21.1606569 1.06085526 17.8381178 9.70199601 5.59646761 1.26562163 5.59646761 1.26562163 1.2
its svg file so i decided to go with more obvious "naming" route ;)

2017-07-06 08:21 UTC, pavveu commented on client/app/styles/mixins/mixins.scss
> +@mixin typo($font-size, $line-height, $font-weight:null) {
typo as typograhy but shorter :P

2017-07-06 17:00 UTC, byPawel commented on client/app/styles/mixins/mixins.scss
> +@mixin bck-color ($background, $color) {
i try to make the names of the mixins as short as possible ;) but since most IDE's can now prompt the syntax - it might be a good idea.

2017-07-06 17:00 UTC, byPawel commented on client/app/styles/mixins/mixins.scss
> +  -webkit-transition: all 0.4s ease-in-out;
i started using this mixin long time ago, but i think that it won't hurt to leave it as it is

2017-07-06 17:00 UTC, byPawel commented on client/app/styles/mixins/mixins.scss
> +@mixin simple-button-wide($text-color, $bck-color: #ffffff, $border: null, $padding-horizontal: null, $padding-vertical: null) {
we could use the simple one and then just overwrite the padding by writing padding values again, or by writing padding different way ;) so i agree that this can be refactored - however since we can have some code suggestions -> see the pic below, i dont think it's necessary  - it's easier to use the way it is  
![screen shot 2017-07-06 at 10 31 35](https://user-images.githubusercontent.com/108490/27902550-6b9d00ac-6236-11e7-86ee-eaa6bf962ea0.png)

2017-07-07 15:55 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +  -webkit-transition: all 0.4s ease-in-out;
OK

2017-07-07 15:58 UTC, pawelniewie commented on client/app/styles/mixins/mixins.scss
> +@mixin simple-button-wide($text-color, $bck-color: #ffffff, $border: null, $padding-horizontal: null, $padding-vertical: null) {
I was thinking more about including simple into wide as there are a few declarations that repeat. What do you think?

2017-07-07 15:59 UTC, pawelniewie approved these changes

2017-07-07 16:01 UTC, pawelniewie commented
Please rename `typo` and `bck-color` other than that it's OK.

Good job!

2017-07-12 19:54 UTC, closed without merging